---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: Nightly


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs every 5min
  schedule:
    - cron: '*/5 * * * *'


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  test:
    name: "[ ref: ${{ matrix.refs }} target: ${{ matrix.target }} ]"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        target:
          - test
        refs:
          - 'master'
          - '0,1'
    steps:

      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ matrix.refs }}

      - name: "git-info.sh"
        run: |

          # Retrieve git info (tags, etc)
          git fetch --all
          make ${TARGET}
        env:
          TARGET: ${{ matrix.target }}
