---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: Test


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:

  # Runs on master Branch and Tags
  push:


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  test:
    name: "[ ref: ${{ matrix.target }} ]"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        target:
          - test
    steps:

      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "git-info.sh"
        run: |

          # Retrieve git info (tags, etc)
          git fetch --all
          git branch --no-color
          git rev-parse HEAD
          make ${TARGET}
        env:
          TARGET: ${{ matrix.target }}
